[gcp_service_account]
type = "service_account"
project_id = "stoked-champion-436904-d8"
private_key_id = "391f446d8a3a940bad8b483ee26c8e290acfa178"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDCilzo6hevzOzH
n5036crwtBgwAxQSnoahy4EwTefiBn1ACtpJvPmToJbY0MzWNSU+FqNknanejhHg
... (중략) ...
MsZ2hDyqKAKL7abEu8nDcw==
-----END PRIVATE KEY-----"""
client_email = "sheets-access@stoked-champion-436904-d8.iam.gserviceaccount.com"
client_id = "106629405623582245413"
