[gcp_service_account]
type = "service_account"
project_id = "stoked-champion-436904-d8"
private_key_id = "391f446d8a3a940bad8b483ee26c8e290acfa178"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDCilzo6hevzOzH\\nn5036crwtBgwAxQSnoahy4EwTefiBn1ACtpJvPmToJbY0MzWNSU+FqNknanejhHg\\nRHyZRuRmz0ZY8oP+NWU3Vm1ug4ye9fYlv7wV61xDsMqdHxN6cpiENTyGX1SvIcvf\\n...중략...\\nMsZ2hDyqKAKL7abEu8nDcw==\\n-----END PRIVATE KEY-----\\n"
client_email = "sheets-access@stoked-champion-436904-d8.iam.gserviceaccount.com"
client_id = "106629405623582245413"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-access%40stoked-champion-436904-d8.iam.gserviceaccount.com"
